
seml:
  executable: 'eval_seml.py'
  db_collection: 'priornet-thesis-eval'
  output_dir: '~/logs'
  
slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 2
    time: 0-08:00
    partition: gpu_all

fixed:
  in_domain_dataset: MNIST
  ood_dataset: OMNIGLOT
  model_dir: "./runtime-model"
  data_dir: "./runtime-data"
  batch_size: 64
  logdir: "/nfs/homedirs/giri/priornet/logs"
  run_eval: True
  run_attack: False
  epsilon_list: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
  attack_type: "PGD"
  attack_norm: "inf"
    