
seml:
  executable: 'eval_seml.py'
  db_collection: 'priornet-thesis-attack-new'
  output_dir: '~/logs'
  
slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 2
    time: 03-00:00
    partition: gpu_all

fixed:
  in_domain_dataset: MNIST
  ood_dataset: CIFAR10
  model_dir: "./runtime-model-vgg6-50epochs"
  data_dir: "./runtime-data"
  batch_size: 64
  use_train_dataset: False
  use_val_dataset: False
  dataset_size_limit: None
  target_precision: 100
  logdir: "/nfs/homedirs/giri/priornet/logs"
  run_eval: False
  rpn_mc_samples: 100
  rpn_reduction: 'mean' # ['mean', 'median', 'log_cosh']
  run_attack: True
  epsilon_list: [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
  threshold: 0.27268
  attack_type: "misclassify" # one of ['misclassify', 'ood-detect']
  attack_strategy: "PGD"
  attack_criteria: "confidence" # use ['confidence', 'diff_entropy', 'mutual_info']
  attack_norm: "inf"
  max_steps: 10
  run_certification: False
  certify_task: "ood-detect"
  certify_only_ood: False
  n0: 100
  n: 1000
  sigma: 0.2
  uncertainty_measure: CONFIDENCE
  uncertainty_measure_threshold: -0.5947
  
    
