
seml:
  executable: 'eval_seml.py'
  db_collection: 'priornet-thesis-certify'
  output_dir: '~/logs'
  
slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 2
    time: 0-08:00
    partition: gpu_all

fixed:
  in_domain_dataset: MNIST
  ood_dataset: OMNIGLOT
  model_dir: "./runtime-model-vgg6-50epochs-robust"
  data_dir: "./runtime-data"
  batch_size: 64
  use_train_dataset: True
  use_val_dataset: False
  dataset_size_limit: 5000
  logdir: "/nfs/homedirs/giri/priornet/logs"
  run_eval: False
  run_attack: False
  epsilon_list: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
  threshold: -0.16398
  attack_type: "ood-detect" # one of ['misclassify', 'ood-detects']
  attack_strategy: "PGD"
  attack_criteria: "confidence" # use ['confidence', 'diff_entropy']
  attack_norm: "inf"
  max_steps: 10
  run_certification: True
  certify_task: "ood-detect"
  n0: 100
  n: 1000
  sigma: 0.2
  uncertainty_measure: CONFIDENCE
  uncertainty_measure_threshold: -0.5947
  
    
