
seml:
  executable: 'trainer_seml.py'
  db_collection: 'priornet-thesis-advgen-train-cifar10-new'
  output_dir: '~/logs'

slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 8
    time: 30-00:00
    partition: gpu_all
    nodelist: gpu04

grid:
  learning_rate:
    type: loguniform
    min: 1e-3
    max: 1e-6
    num: 3
  target_precision:
    type: choice
    options:
      - 100
      - 1000
  gamma: # OOD loss weight
    type: choice
    options:
      - 1.0
      - 5.0
      - 10.0

fixed:
  in_domain_dataset: CIFAR10
  input_image_size: 32
  num_classes: 10
  ood_dataset: CIFAR100
  model_arch: vgg16
  rpn_wrapper: None # ['simple', 'count', 'normal', None]
  rpn_mc_samples: 100
  rpn_reduction: 'mean' # ['mean', 'median', 'log_cosh']
  rpn_sigma: 0.2
  fc_layers: [100,90,80,50]
  train_stepwise: True
  val_every_steps: 100
  num_epochs: 100
  min_train_epochs: 24000
  patience: 10
  num_channels: 3
  grad_clip_value: 10.0
  use_cyclic_lr: True
  cyclic_lr_pct_start: 0.35
  optimizer: ADAM
  add_ce_loss: True
  ce_weight: 1.0
  reverse_KL: False
  drop_rate: 0.05
  weight_decay: 0.0
  model_dir: "./runtime-model-vgg16-100epochs-cifar10"
  resume_from_ckpt: False
  augment_data: True
  data_dir: "./runtime-data"
  lr_decay_milestones: [1]
  batch_size: 128
  dataset_size_limit: None
  adv_training: False
  only_out_in_adv: False
  adv_training_type: "ood-detect" # ['normal', 'ood-detect']
  adv_attack_type: "PGD"
  adv_epsilon: 0.5
  adv_attack_criteria: "diff_entropy"
  use_fixed_threshold: False
  known_threshold_value: 0.0
  adv_model_dir: ""
  adv_persist_images: True
  pgd_norm: "inf"
  pgd_max_steps: 10 
  logdir: "/nfs/homedirs/giri/priornet/logs"
  
