
seml:
  executable: 'trainer_seml.py'
  db_collection: 'priornet-thesis-advgen-train'
  output_dir: '~/logs'

slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 8
    time: 30-00:00
    partition: gpu_all

fixed:
  in_domain_dataset: MNIST
  input_image_size: 28
  num_classes: 10
  ood_dataset: OMNIGLOT
  model_arch: vgg6
  rpn_wrapper: None # ['simple', 'count', 'normal', None]
  rpn_mc_samples: 100
  rpn_reduction: 'mean' # ['mean', 'median', 'log_cosh']
  rpn_sigma: 0.2
  fc_layers: [100,90,80,50]
  train_stepwise: False
  val_every_steps: 100
  num_epochs: 50
  min_train_epochs: 25
  patience: 10
  num_channels: 1
  learning_rate: 0.0001
  grad_clip_value: 10.0
  use_cyclic_lr: False
  cyclic_lr_pct_start: 0.35
  add_ce_loss: False
  ce_weight: 0.05
  reverse_KL: False
  gamma: 1.0 # OOD loss weight
  drop_rate: 0.05
  weight_decay: 0.0
  target_precision: 100
  model_dir: "./runtime-model-vgg6-50epochs-adgen-robust-dentropy-out"
  resume_from_ckpt: False
  augment_data: False
  data_dir: "./runtime-data"
  lr_decay_milestones: [1]
  batch_size: 64
  dataset_size_limit: None
  adv_training: False
  only_out_in_adv: False
  adv_training_type: "ood-detect" # ['normal', 'ood-detect']
  adv_attack_type: "PGD"
  adv_epsilon: 0.5
  adv_attack_criteria: "diff_entropy"
  use_fixed_threshold: False
  known_threshold_value: 0.0
  adv_model_dir: ""
  adv_persist_images: True
  pgd_norm: "inf"
  pgd_max_steps: 10 
  logdir: "/nfs/homedirs/giri/priornet/logs"
  
