
seml:
  executable: 'trainer_seml.py'
  db_collection: 'priornet-thesis'
  output_dir: '~/logs'

slurm:
  name: 'dirchletpriornet'
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem:  8G
    cpus-per-task: 2
    time: 03-00:00 # increase time for adv training!! like 30-00:00
    partition: gpu_all

fixed:
  in_domain_dataset: MNIST
  input_image_size: 28
  num_classes: 10
  ood_dataset: OMNIGLOT
  model_arch: vgg6
  fc_layers: [100,90,80,50]
  num_epochs: 50
  num_channels: 1
  learning_rate: 0.0001
  drop_rate: 0.05
  target_precision: 100
  model_dir: "./runtime-model"
  resume_from_ckpt: False
  data_dir: "./runtime-data"
  lr_decay_milestones: [1]
  batch_size: 64
  adv_training: False
  adv_attack_type: "FGSM"
  adv_epsilon: 0.5
  adv_attack_criteria: "diff_entropy"
  adv_model_dir: ""
  adv_persist_images: False
  pgd_norm: "inf"
  pgd_max_steps: 100 
  logdir: "/nfs/homedirs/giri/priornet/logs"
  
